services:
  postgres:
    image: postgres:16-bookworm
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    image: failcase/ticket-store-backend:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/home/django
    user: root
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  postgres_data:
