services:
  postgres:
    image: postgres:16-bookworm
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  ticket-store-backend:
    image: failcase/ticket-store-backend:770ec66
    restart: unless-stopped
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
    volumes:
      - media:/home/django/media:rw
      - staticfiles:/home/django/staticfiles:rw

volumes:
  postgres_data:
  media:
  staticfiles:

networks:
  default:
    external: true
    name: ${NPM_NETWORK_NAME:-frontend}
